export const TrackObjectFull: SpotifyApi.TrackObjectFull = {
  album: {
    album_type: 'compilation',
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/0LyfQWJT6nXafLPZqxe9Of',
        },
        href: 'https://api.spotify.com/v1/artists/0LyfQWJT6nXafLPZqxe9Of',
        id: '0LyfQWJT6nXafLPZqxe9Of',
        name: 'Various Artists',
        type: 'artist',
        uri: 'spotify:artist:0LyfQWJT6nXafLPZqxe9Of',
      },
    ],
    available_markets: [
      'AD',
      'AE',
      'AG',
      'AL',
      'AM',
      'AO',
      'AR',
      'AT',
      'AU',
      'AZ',
      'BA',
      'BB',
      'BD',
      'BE',
      'BF',
      'BG',
      'BH',
      'BI',
      'BJ',
      'BN',
      'BO',
      'BR',
      'BS',
      'BT',
      'BW',
      'BY',
      'BZ',
      'CA',
      'CD',
      'CG',
      'CH',
      'CI',
      'CL',
      'CM',
      'CO',
      'CR',
      'CV',
      'CW',
      'CY',
      'CZ',
      'DE',
      'DJ',
      'DK',
      'DM',
      'DO',
      'DZ',
      'EC',
      'EE',
      'EG',
      'ES',
      'FI',
      'FJ',
      'FM',
      'FR',
      'GA',
      'GB',
      'GD',
      'GE',
      'GH',
      'GM',
      'GN',
      'GQ',
      'GR',
      'GT',
      'GW',
      'GY',
      'HK',
      'HN',
      'HR',
      'HT',
      'HU',
      'ID',
      'IE',
      'IL',
      'IN',
      'IQ',
      'IS',
      'IT',
      'JM',
      'JO',
      'JP',
      'KE',
      'KG',
      'KH',
      'KI',
      'KM',
      'KN',
      'KR',
      'KW',
      'KZ',
      'LA',
      'LB',
      'LC',
      'LI',
      'LK',
      'LR',
      'LS',
      'LT',
      'LU',
      'LV',
      'LY',
      'MA',
      'MC',
      'MD',
      'ME',
      'MG',
      'MH',
      'MK',
      'ML',
      'MN',
      'MO',
      'MR',
      'MT',
      'MU',
      'MV',
      'MW',
      'MX',
      'MY',
      'MZ',
      'NA',
      'NE',
      'NG',
      'NI',
      'NL',
      'NO',
      'NP',
      'NR',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PG',
      'PH',
      'PK',
      'PL',
      'PS',
      'PT',
      'PW',
      'PY',
      'QA',
      'RO',
      'RS',
      'RW',
      'SA',
      'SB',
      'SC',
      'SE',
      'SG',
      'SI',
      'SK',
      'SL',
      'SM',
      'SN',
      'SR',
      'ST',
      'SV',
      'SZ',
      'TD',
      'TG',
      'TH',
      'TJ',
      'TL',
      'TN',
      'TO',
      'TR',
      'TT',
      'TV',
      'TW',
      'TZ',
      'UA',
      'UG',
      'US',
      'UY',
      'UZ',
      'VC',
      'VE',
      'VN',
      'VU',
      'WS',
      'XK',
      'ZA',
      'ZM',
      'ZW',
    ],
    external_urls: {
      spotify: 'https://open.spotify.com/album/3wIq5okaszSGMxYv4zlzyR',
    },
    href: 'https://api.spotify.com/v1/albums/3wIq5okaszSGMxYv4zlzyR',
    id: '3wIq5okaszSGMxYv4zlzyR',
    images: [
      {
        height: 640,
        url: 'https://i.scdn.co/image/ab67616d0000b27336cfcb2e6bd89adfbe618200',
        width: 640,
      },
      {
        height: 300,
        url: 'https://i.scdn.co/image/ab67616d00001e0236cfcb2e6bd89adfbe618200',
        width: 300,
      },
      {
        height: 64,
        url: 'https://i.scdn.co/image/ab67616d0000485136cfcb2e6bd89adfbe618200',
        width: 64,
      },
    ],
    name: 'Arkade Destinations Tulum',
    release_date: '2018-08-03',
    release_date_precision: 'day',
    total_tracks: 18,
    type: 'album',
    uri: 'spotify:album:3wIq5okaszSGMxYv4zlzyR',
  },
  artists: [
    {
      external_urls: {
        spotify: 'https://open.spotify.com/artist/6JtFllJR7nhh8fa6oGefSj',
      },
      href: 'https://api.spotify.com/v1/artists/6JtFllJR7nhh8fa6oGefSj',
      id: '6JtFllJR7nhh8fa6oGefSj',
      name: 'Late Night Alumni',
      type: 'artist',
      uri: 'spotify:artist:6JtFllJR7nhh8fa6oGefSj',
    },
    {
      external_urls: {
        spotify: 'https://open.spotify.com/artist/6TQj5BFPooTa08A7pk8AQ1',
      },
      href: 'https://api.spotify.com/v1/artists/6TQj5BFPooTa08A7pk8AQ1',
      id: '6TQj5BFPooTa08A7pk8AQ1',
      name: 'Kaskade',
      type: 'artist',
      uri: 'spotify:artist:6TQj5BFPooTa08A7pk8AQ1',
    },
  ],
  available_markets: [
    'AD',
    'AE',
    'AG',
    'AL',
    'AM',
    'AO',
    'AR',
    'AT',
    'AU',
    'AZ',
    'BA',
    'BB',
    'BD',
    'BE',
    'BF',
    'BG',
    'BH',
    'BI',
    'BJ',
    'BN',
    'BO',
    'BR',
    'BS',
    'BT',
    'BW',
    'BY',
    'BZ',
    'CA',
    'CD',
    'CG',
    'CH',
    'CI',
    'CL',
    'CM',
    'CO',
    'CR',
    'CV',
    'CW',
    'CY',
    'CZ',
    'DE',
    'DJ',
    'DK',
    'DM',
    'DO',
    'DZ',
    'EC',
    'EE',
    'EG',
    'ES',
    'FI',
    'FJ',
    'FM',
    'FR',
    'GA',
    'GB',
    'GD',
    'GE',
    'GH',
    'GM',
    'GN',
    'GQ',
    'GR',
    'GT',
    'GW',
    'GY',
    'HK',
    'HN',
    'HR',
    'HT',
    'HU',
    'ID',
    'IE',
    'IL',
    'IN',
    'IQ',
    'IS',
    'IT',
    'JM',
    'JO',
    'JP',
    'KE',
    'KG',
    'KH',
    'KI',
    'KM',
    'KN',
    'KR',
    'KW',
    'KZ',
    'LA',
    'LB',
    'LC',
    'LI',
    'LK',
    'LR',
    'LS',
    'LT',
    'LU',
    'LV',
    'LY',
    'MA',
    'MC',
    'MD',
    'ME',
    'MG',
    'MH',
    'MK',
    'ML',
    'MN',
    'MO',
    'MR',
    'MT',
    'MU',
    'MV',
    'MW',
    'MX',
    'MY',
    'MZ',
    'NA',
    'NE',
    'NG',
    'NI',
    'NL',
    'NO',
    'NP',
    'NR',
    'NZ',
    'OM',
    'PA',
    'PE',
    'PG',
    'PH',
    'PK',
    'PL',
    'PS',
    'PT',
    'PW',
    'PY',
    'QA',
    'RO',
    'RS',
    'RW',
    'SA',
    'SB',
    'SC',
    'SE',
    'SG',
    'SI',
    'SK',
    'SL',
    'SM',
    'SN',
    'SR',
    'ST',
    'SV',
    'SZ',
    'TD',
    'TG',
    'TH',
    'TJ',
    'TL',
    'TN',
    'TO',
    'TR',
    'TT',
    'TV',
    'TW',
    'TZ',
    'UA',
    'UG',
    'US',
    'UY',
    'UZ',
    'VC',
    'VE',
    'VN',
    'VU',
    'WS',
    'XK',
    'ZA',
    'ZM',
    'ZW',
  ],
  disc_number: 1,
  duration_ms: 340965,
  explicit: false,
  external_ids: {
    isrc: 'GBKPL1817555',
  },
  external_urls: {
    spotify: 'https://open.spotify.com/track/2Vrg4Ar4v8KECMdwck1DRl',
  },
  href: 'https://api.spotify.com/v1/tracks/2Vrg4Ar4v8KECMdwck1DRl',
  id: '2Vrg4Ar4v8KECMdwck1DRl',
  is_local: false,
  name: 'Low - Kaskade Remix',
  popularity: 44,
  preview_url:
    'https://p.scdn.co/mp3-preview/28dcb596c08dc70be1334f97637973f5cf9f4cdd?cid=a02b6c26dd38440c96aa029524fef3e7',
  track_number: 2,
  type: 'track',
  uri: 'spotify:track:2Vrg4Ar4v8KECMdwck1DRl',
};
