coverage:
  status:
    project:
      default: off
      auth-token:
        flags:
          - auth-token
      cli:
        flags:
          - cli
      core:
        flags:
          - core
      library:
        flags:
          - library
      utils:
        flags:
          - utils

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
        target: auto
      - type: patch
        target: 90%
  individual_flags:
    - name: auth-token
      paths:
        - packages/auth-token
    - name: cli
      paths:
        - packages/cli
    - name: core
      paths:
        - packages/core
    - name: library
      paths:
        - packages/library
    - name: utils
      paths:
        - packages/utils
