name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  eslint:
    name: ESLint
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Lint
        run: yarn lint

  tests:
    name: Test on Node ${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ['14', '16', '17', '18']
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node v${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run tests
        run: yarn test --coverage

  integration:
    name: Integration tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ['18']
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node v${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run tests
        run: yarn test:integration

  build:
    name: Build packages
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build packages
        run: yarn build
