name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  eslint:
    name: ESLint
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Lint
        run: yarn lint
  tests:
    name: Test on Node ${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ['14', '16', '17']
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node v${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test --coverage --verbose
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        if: matrix.node == '17'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: ./coverage/coverage-final.json
          name: codecov-spotifly
          verbose: true
  build:
    name: Build packages
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Build packages
        run: yarn build
