name: Deploy docs (test)

on:
  pull_request:
    branches: [main]
    paths: [docs/**]

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: yarn
      - name: Test build
        working-directory: ./docs
        run: |
          yarn install
          yarn build
