name: Coverage

on:
  push:
    branches:
      - main
    paths:
      - '**.ts'

coverage:
  name: Get coverage for proj/${{ matrix.project }}
  needs: tests
  runs-on: ${{ matrix.os }}
  strategy:
    matrix:
      os: [ubuntu-latest]
      project:
        [
          'auth-token',
          'cli',
          'core',
          'core-types',
          'library',
          'utils',
          'website',
        ]
  steps:
    - uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: 'yarn'
    - name: Install dependencies
      run: yarn install:ci
    - name: Run tests
      run: yarn test:pkg ${{ matrix.project }} --coverage
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        flags: ${{ matrix.project }}
        files: ./coverage/coverage-final.json
        name: codecov-spotifly
        verbose: true
